# Generated by Django 5.1.1 on 2024-09-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30)),
            ],
        ),
    ]
